routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/tes', function () {
    return view('tes');
});

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {

	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/siswa', 'SiswaController@index')->name('siswa.index');
	Route::get('/siswa/edit/{id}', 'SiswaController@edit')->name('siswa.edit');
	Route::get('/siswa/history/{id}', 'SiswaController@show')->name('siswa.show');
	Route::get('/siswa/tambah', 'SiswaController@create')->name('siswa.create');
	Route::get('/books/history/{$id}', 'BooksController@show')->name('books.show');

	Route::post('/siswa/store', 'SiswaController@store')->name('siswa.store');
	Route::put('/siswa/update/{id}', 'SiswaController@update')->name('siswa.update');
	Route::delete('/siswa/delete/{id}', 'SiswaController@destroy')->name('siswa.destroy');


	Route::resources([
		'book_category' => 'BookCategoryController',
		'books' => 'BookController',
		'borrow' => 'BorrowController'

	]);
	Route::get('/borrows/{borrow}/return', 'BorrowController@return')->name('borrows.return');
	Route::put('/borrows/{borrow}/return', 'BorrowController@returnPost')->name('borrows.returnPost');
});


Auth::routes();

app/BookCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BookCategory extends Model
{
    //
}

app/Http/Controllers/BookCategoryController.php
<?php

namespace App\Http\Controllers;

use App\BookCategory;
use Illuminate\Http\Request;

class BookCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = BookCategory::all();
        return view('book_category.index', compact('category')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('book_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $siswa = new BookCategory;
        $siswa->name = $request->name;
        $siswa->description = $request->description;
        $siswa->save();
        return redirect()->route('book_category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = BookCategory::findOrFail($id);
        return view('book_category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $siswa = BookCategory::findOrFail($id);
        $siswa->name = $request->name;
        $siswa->description = $request->description;
        $siswa->update();
        return redirect()->route('book_category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = BookCategory::findOrFail($id);
        $siswa->delete();
        return redirect()->route('book_category.index');
    }
}

resources/views/book_category/create.blade.php
@extends('layouts.template')

@section('content')
<div class="x_panel">
    <div class="x_title">
        <h2>Tambah Data Buku</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
    <!-- start form for validation -->
        <form action="{{ route('book_category.store') }}" method="post">
            @csrf
                <div class="form-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" 
                            id="name" placeholder="Masukkan Nama">
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <textarea class="form-control" name="description" 
                            id="description" rows="4"></textarea>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">Simpan</button>
        </form>
    <!-- end form for validations -->
    </div>
</div>
@endsection
@section('content2')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Data Kategori</div>
                    <div class="card-body">
                        <form action="{{ route('book_category.store') }}" method="post">
                            @csrf
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Nama</label>
                                            <input type="text" name="name" class="form-control" 
                                            id="name" placeholder="Masukkan Nama">
                                        </div>
                                        <div class="form-group">
                                            <label for="description">Deskripsi</label>
                                            <textarea class="form-control" name="description" 
                                            id="description" rows="4"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-danger">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/book_category/edit.blade.php
@extends('layouts.template')

@section('content')
<div class="x_panel">
    <div class="x_title">
        <h2>Ubah Data Siswa</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
    <!-- start form for validation -->
        <form action="{{ route('book_category.update', $category->id) }}" method="post">
            @csrf
            @method('put')
                <div class="form-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" 
                            id="name" placeholder="Masukkan Nama" value="{{ $category->name }}">
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <textarea class="form-control" name="description" 
                            id="description" rows="4">{{ $category->description }}</textarea>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">Simpan</button>
        </form>
    <!-- end form for validations -->
    </div>
</div>
@endsection
@section('content2')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Ubah Data Kategori</div>
                    <div class="card-body">
                        <form action="{{ route('book_category.update', $category->id) }}" method="post">
                            @csrf
                            @method('put')
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Nama</label>
                                            <input type="text" name="name" class="form-control" 
                                            id="name" placeholder="Masukkan Nama" value="{{ $category->name }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="description">Deskripsi</label>
                                            <textarea class="form-control" name="description" 
                                            id="description" rows="4">{{ $category->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-danger">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/book_category/index.blade.php
@extends('layouts.template')

@section('content')
<div class="col-md-12 col-sm-6">
  <div class="row">
    <div class="x_panel">
      <div class="x_title">
        <h2>Data Kategori</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li>
              <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li>
              <a href="{{ route('book_category.create') }}">
                <button type="button" class="btn btn-primary btn-sm">Tambah</button>
              </a>
            </li>
            <li>
              <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table class="table table-striped">
          <thead>
            <tr style="text-align: center;">
                <th scope="col">No</th>
                <th scope="col">Nama</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Pilihan</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($category as $i => $item)
            <tr style="text-align: center;">
                <td>{{ $i+1 }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->description }}</td>
                <td>
                  <form action="{{ route('book_category.destroy',$item->id) }}" method="post">
                  <a href="{{ route('book_category.edit',$item->id) }}">
                    <button type="button" class="btn btn-success">Ubah</button>
                  </a>
                  @csrf 
                  @method('delete')
                    <button type="submit" class="btn btn-danger" 
                    onclick="return confirm('Yakin ingin dihapus ?')">Hapus</button>
                  </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> 
@endsection
@section ('content2')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
          <div class="card">
            <div class="card-header">
            Data Kategori
            <a href="{{ route('book_category.create') }}">
                <button type="button" class="btn btn-primary">Tambah</button>
                </a>
            </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Nama</th>
                                <th scope="col">Deskripsi</th>
                                <th scope="col">Menu</th>
                            </tr>
                        </thead>
                            <tbody>
                              @foreach ($category as $i => $item)
                              <tr>
                                  <td>{{ $i+1 }}</td>
                                  <td>{{ $item->name }}</td>
                                  <td>{{ $item->description }}</td>
                                  <td>
                                    <form action="{{ route('book_category.destroy',$item->id) }}" method="post">
                                    <a href="{{ route('book_category.edit',$item->id) }}">
                                      <button type="button" class="btn btn-success">Ubah</button>
                                    </a>
                                    @csrf 
                                    @method('delete')
                                      <button type="submit" class="btn btn-danger" 
                                      onclick="return confirm('Yakin Nih Dihapus ?')">Hapus</button>
                                    </form>
                                </td>
                              </tr>
                              @endforeach
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection